# Generated by Django 6.0.1 on 2026-01-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное название')),
                ('short_name', models.CharField(max_length=50, verbose_name='Сокращенное название')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('enrollment_year', models.PositiveIntegerField(verbose_name='Год поступления')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='university_app.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'ordering': ['full_name'],
            },
        ),
    ]
